version: "3"
#test
services:
  nurds:
    container_name: nurds
    image: lsastre/nurds-esp:latest
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nurds.entrypoints=http"
      - "traefik.http.routers.nurds.rule=Host(`nurds.selfhost.ar`)"
      - "traefik.http.middlewares.nurds-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nurds.middlewares=nurds-https-redirect"
      - "traefik.http.routers.nurds-secure.entrypoints=https"
      - "traefik.http.routers.nurds-secure.rule=Host(`nurds.selfhost.ar`)"
      - "traefik.http.routers.nurds-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.nurds-secure.tls=true"
      - "traefik.http.routers.nurds-secure.service=nurds"
      - "traefik.http.services.nurds.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"


networks:
  proxy:
    external: true